// automatically generated by the FlatBuffers compiler, do not modify

package AllWatchSerialize;

public final class Layout {
    public static final short Text = 0;
    public static final short MultilineText = 1;
    public static final short WithIcon = 2;
    public static final short Menu = 3;
    public static final String[] names = {"Text", "MultilineText", "WithIcon", "Menu",};

    private Layout() {
    }

    public static String name(int e) {
        return names[e];
    }
}

